name: notepad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - Stable versions
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  
  # State Management
  provider: ^6.1.2
  
  # Local Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  
  # UI
  google_fonts: ^6.2.1
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.4.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
